import { useState, useCallback, useEffect, useRef } from 'react'
import html2canvas from 'html2canvas'
import FilterBar from './FilterBar'
import Chart from './Chart'
import AnimatedNumber from './AnimatedNumber'
import { LOCATIONS, METRICS, getPlutoQuip } from './locations'
import { fetchWeatherData, computeSummary, toCSV } from './api'
import { playBloop, playWhoosh, playChime, playClick, isMuted, toggleMute } from './sounds'
import type { WeatherMetric, LocationResult, Location, ChartType } from './types'

function parseUrlParams(): {
  metrics?: WeatherMetric[]
  locations?: string[]
  start?: string
  end?: string
} {
  const params = new URLSearchParams(window.location.search)
  const validMetrics = new Set(METRICS.map(m => m.id))

  const metrics = params.get('metrics')?.split(',').filter(m => validMetrics.has(m as WeatherMetric)) as WeatherMetric[] | undefined
  const locations = params.get('locations')?.split(',')
  const start = params.get('start') ?? undefined
  const end = params.get('end') ?? undefined

  return {
    metrics: metrics?.length ? metrics : undefined,
    locations: locations?.length ? locations : undefined,
    start,
    end,
  }
}

function buildShareUrl(metrics: WeatherMetric[], locations: string[], start: string, end: string): string {
  const params = new URLSearchParams({
    metrics: metrics.join(','),
    locations: locations.join(','),
    start,
    end,
  })
  return `${window.location.origin}${window.location.pathname}?${params}`
}

// Determine background gradient based on dominant metric
function getWeatherGradient(metrics: WeatherMetric[]): string {
  if (metrics.length === 0) return ''
  const primary = metrics[0]
  switch (primary) {
    case 'precipitation_sum': return 'linear-gradient(150deg, #b0c4d8 0%, #d0dde8 50%, #e8eef4 100%)'
    case 'sunshine_duration': return 'linear-gradient(150deg, #f5e6b0 0%, #fef3d0 50%, #fff9e8 100%)'
    case 'temperature_2m_max': return 'linear-gradient(150deg, #f0c8a8 0%, #f8e0cc 50%, #fef0e4 100%)'
    case 'temperature_2m_min': return 'linear-gradient(150deg, #a8c8e8 0%, #c8ddf0 50%, #e4eef8 100%)'
    case 'snowfall_sum': return 'linear-gradient(150deg, #d8e4f0 0%, #e8eff6 50%, #f4f8fc 100%)'
    case 'wind_speed_10m_max': return 'linear-gradient(150deg, #c0d8d0 0%, #dce8e4 50%, #eef4f0 100%)'
    default: return ''
  }
}

function HomeBtn() {
  return (
    <a href="https://sakhalteam.github.io/" className="home-btn" title="Back to island">
      <svg width="20" height="12" viewBox="0 0 32 18" fill="currentColor" aria-hidden="true">
        <path d="M 4,10 C 5,4 9,2 14,3 C 18,4 20,2 24,4 C 28,6 29,11 26,15 C 22,18 12,18 6,15 C 2,13 2,11 4,10 Z" />
      </svg>
      sakhalteam
    </a>
  )
}

const TODAY = new Date().toISOString().split('T')[0]

export default function App() {
  const urlParams = parseUrlParams()
  const [selectedMetrics, setSelectedMetrics] = useState<WeatherMetric[]>(urlParams.metrics ?? ['precipitation_sum'])
  const [selectedLocations, setSelectedLocations] = useState<string[]>(urlParams.locations ?? ['lynnwood'])
  const [allLocations, setAllLocations] = useState<Location[]>(LOCATIONS)
  const [startDate, setStartDate] = useState(urlParams.start ?? TODAY)
  const [endDate, setEndDate] = useState(urlParams.end ?? TODAY)
  const [results, setResults] = useState<LocationResult[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [activeChartMetric, setActiveChartMetric] = useState<WeatherMetric>('precipitation_sum')
  const [chartType, setChartType] = useState<ChartType>('bar')
  const [copied, setCopied] = useState(false)
  const [soundMuted, setSoundMuted] = useState(true)
  const [exporting, setExporting] = useState(false)
  const reportRef = useRef<HTMLDivElement>(null)
  const hasAutoGenerated = useRef(false)

  // Sync selections to URL
  useEffect(() => {
    const url = buildShareUrl(selectedMetrics, selectedLocations, startDate, endDate)
    window.history.replaceState(null, '', url)
  }, [selectedMetrics, selectedLocations, startDate, endDate])

  // Weather-appropriate background
  useEffect(() => {
    const gradient = getWeatherGradient(selectedMetrics)
    if (gradient) {
      document.body.style.background = gradient
      document.body.style.transition = 'background 0.8s ease'
    }
    return () => { document.body.style.background = '' }
  }, [selectedMetrics])

  const toggleMetric = useCallback((id: WeatherMetric) => {
    playBloop()
    setSelectedMetrics(prev =>
      prev.includes(id) ? prev.filter(m => m !== id) : [...prev, id]
    )
  }, [])

  const toggleLocation = useCallback((id: string) => {
    playBloop()
    setSelectedLocations(prev =>
      prev.includes(id) ? prev.filter(l => l !== id) : [...prev, id]
    )
  }, [])

  const addLocation = useCallback((loc: Location) => {
    playBloop()
    setAllLocations(prev => {
      if (prev.some(l => l.id === loc.id)) return prev
      return [...prev, loc]
    })
    setSelectedLocations(prev => prev.includes(loc.id) ? prev : [...prev, loc.id])
  }, [])

  const generate = useCallback(async () => {
    playWhoosh()
    setLoading(true)
    setError(null)
    setResults([])

    try {
      const locations = selectedLocations.map(id => allLocations.find(l => l.id === id)!).filter(Boolean)
      const fetched = await Promise.all(
        locations.map(async loc => {
          const data = await fetchWeatherData(loc, selectedMetrics, startDate, endDate)
          return { location: loc, daily: data.daily }
        })
      )
      setResults(fetched)
      setActiveChartMetric(selectedMetrics[0])
      playChime()
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Something went wrong')
    } finally {
      setLoading(false)
    }
  }, [selectedMetrics, selectedLocations, allLocations, startDate, endDate])

  // Auto-generate if URL has all params
  useEffect(() => {
    if (hasAutoGenerated.current) return
    if (urlParams.metrics && urlParams.locations && urlParams.start && urlParams.end) {
      hasAutoGenerated.current = true
      generate()
    }
  }, []) // eslint-disable-line react-hooks/exhaustive-deps

  const reset = useCallback(() => {
    playClick()
    setSelectedMetrics(['precipitation_sum'])
    setSelectedLocations(['lynnwood'])
    setStartDate(TODAY)
    setEndDate(TODAY)
    setResults([])
    setError(null)
  }, [])

  const exportCSV = useCallback(() => {
    const csv = toCSV(results, selectedMetrics)
    const blob = new Blob([csv], { type: 'text/csv' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `weather-report-${startDate}-to-${endDate}.csv`
    a.click()
    URL.revokeObjectURL(url)
  }, [results, selectedMetrics, startDate, endDate])

  const exportPNG = useCallback(async () => {
    if (!reportRef.current) return
    setExporting(true)
    try {
      const canvas = await html2canvas(reportRef.current, {
        backgroundColor: '#eef6ff',
        scale: 2,
        logging: false,
        useCORS: true,
      })

      // Add watermark
      const ctx = canvas.getContext('2d')!
      ctx.font = '14px Nunito, system-ui, sans-serif'
      ctx.fillStyle = 'rgba(100, 140, 180, 0.5)'
      ctx.textAlign = 'right'
      ctx.fillText('sakhalteam.github.io/weather-report', canvas.width - 20, canvas.height - 12)

      const link = document.createElement('a')
      link.download = `weather-report-${startDate}-to-${endDate}.png`
      link.href = canvas.toDataURL('image/png')
      link.click()
    } finally {
      setExporting(false)
    }
  }, [startDate, endDate])

  const hasPluto = results.some(r => r.location.isEasterEgg)

  return (
    <>
      <HomeBtn />

      {/* Sound toggle */}
      <button
        className="sound-toggle"
        onClick={() => { toggleMute(); setSoundMuted(isMuted()) }}
        title={soundMuted ? 'Unmute sounds' : 'Mute sounds'}
      >
        {soundMuted ? '\u{1F507}' : '\u{1F50A}'}
      </button>

      <div style={{ maxWidth: 780, margin: '0 auto', padding: '60px 16px 40px' }}>
        <header style={{ textAlign: 'center', marginBottom: 32 }}>
          <h1 style={{ fontSize: 32, fontWeight: 800, color: 'var(--text)' }}>
            Weather Report
          </h1>
          <p style={{ fontSize: 15, color: 'var(--text-muted)', marginTop: 4 }}>
            Compare weather across locations. Yes, including Pluto.
          </p>
        </header>

        <FilterBar
          selectedMetrics={selectedMetrics}
          selectedLocations={selectedLocations}
          allLocations={allLocations}
          startDate={startDate}
          endDate={endDate}
          loading={loading}
          onToggleMetric={toggleMetric}
          onToggleLocation={toggleLocation}
          onAddLocation={addLocation}
          onStartDate={setStartDate}
          onEndDate={setEndDate}
          onGenerate={generate}
          onReset={reset}
        />

        {error && (
          <div style={{ textAlign: 'center', marginTop: 24, color: '#e74c3c', fontWeight: 600 }}>
            {error}
          </div>
        )}

        {/* Empty state */}
        {results.length === 0 && !loading && !error && (
          <div className="empty-state">
            <div className="empty-icon">{'\u{1F326}\u{FE0F}'}</div>
            <div className="empty-text">Pick some weather, choose your locations, and hit Generate!</div>
            <div className="empty-hint">Pro tip: add Pluto for a reality check on your local weather complaints</div>
          </div>
        )}

        {results.length > 0 && (
          <div ref={reportRef} style={{ marginTop: 32 }}>
            {/* Report title for PNG export context */}
            <div className="report-header">
              <span className="report-title">Weather Report</span>
              <span className="report-dates">{startDate} to {endDate}</span>
            </div>

            {/* Summary Cards — one card per location, all metrics inside */}
            <div style={{
              display: 'grid',
              gridTemplateColumns: `repeat(auto-fill, minmax(200px, 1fr))`,
              gap: 14,
              marginBottom: 24,
            }}>
              {results.map(r => (
                <div
                  key={r.location.id}
                  className={`summary-card ${r.location.isEasterEgg ? 'pluto' : ''}`}
                >
                  <div className="emoji">{r.location.emoji}</div>
                  <div className="location-name">{r.location.name}</div>
                  <div className="stat-list">
                    {selectedMetrics.map(metric => {
                      const info = METRICS.find(m => m.id === metric)!
                      const summaryText = computeSummary(r.daily, metric)
                      return (
                        <div key={metric} className="stat-row">
                          <span className="stat-value">
                            <AnimatedNumber value={summaryText} />
                          </span>
                          <span className="stat-label">{info.emoji} {info.summaryLabel}</span>
                        </div>
                      )
                    })}
                  </div>
                  {r.location.isEasterEgg && (
                    <div className="pluto-quip">{getPlutoQuip(selectedMetrics[0])}</div>
                  )}
                </div>
              ))}
            </div>

            {hasPluto && (
              <div className="pluto-toast">
                Data from Pluto is simulated. Actual conditions may include nitrogen ice storms and existential dread.
              </div>
            )}

            {/* Chart Metric Selector */}
            {selectedMetrics.length > 1 && (
              <div style={{ display: 'flex', gap: 8, marginTop: 20, marginBottom: 12, flexWrap: 'wrap' }}>
                {selectedMetrics.map(m => {
                  const info = METRICS.find(i => i.id === m)!
                  return (
                    <button
                      key={m}
                      className={`pill ${activeChartMetric === m ? 'active' : ''}`}
                      onClick={() => { setActiveChartMetric(m); playBloop() }}
                      style={{ fontSize: 13, padding: '6px 12px' }}
                    >
                      {info.emoji} {info.label}
                    </button>
                  )
                })}
              </div>
            )}

            {/* Chart */}
            <div style={{ marginTop: 12 }}>
              <Chart
                results={results}
                metric={activeChartMetric}
                chartType={chartType}
                onToggleChartType={() => {
                  setChartType(prev => prev === 'bar' ? 'line' : 'bar')
                  playBloop()
                }}
              />
            </div>
          </div>
        )}

        {/* Export & Share buttons (outside reportRef so they don't appear in PNG) */}
        {results.length > 0 && (
          <div style={{ display: 'flex', justifyContent: 'center', gap: 12, marginTop: 24, flexWrap: 'wrap' }}>
            <button className="btn-export" onClick={exportCSV}>
              Export CSV
            </button>
            <button className="btn-export" onClick={exportPNG} disabled={exporting}>
              {exporting ? 'Exporting...' : 'Export PNG'}
            </button>
            <button
              className="btn-export"
              onClick={() => {
                navigator.clipboard.writeText(
                  buildShareUrl(selectedMetrics, selectedLocations, startDate, endDate)
                )
                setCopied(true)
                playChime()
                setTimeout(() => setCopied(false), 2000)
              }}
            >
              {copied ? 'Copied!' : 'Copy Link'}
            </button>
          </div>
        )}
      </div>
    </>
  )
}
